### ISSUE TITLE
Font v TEITOku

### ISSUE THREAD

**Issue by hladkab** [ufal/media-irozhlas#22]
Je možno v TEITOku použít stejný font jako je v LINDATí hlaviččce?

**Comment by matyaskopp** [comment]
upraveno: 
```css
#content p, #content td {
    font-family: "Source Sans Pro", -apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
    font-size: 1.1rem;
    line-height: 1.4;
}
```
